### ISSUE TITLE
improve pen-up time travel

### ISSUE THREAD

**Issue by MAKIO135** [nornagon/optimize-paths#2]
When using Saxi's option to sort paths I noticed that after a path was done, it started the next from where it had begun the path instead of the end. So after finding this package and doing some investigation (https://observablehq.com/@makio135/saxi-paths-optimization-study) I found a fix to improve this.

Right now optimize-paths reorder function will work like this:  
![untitled (32)](https://user-images.githubusercontent.com/1162231/167810769-d15f72aa-3e56-49b9-be1b-e2a3da6bbb00.png)

While the improved version should be like this:
![untitled (33)](https://user-images.githubusercontent.com/1162231/167810931-136cc891-5cd6-4fa6-8951-001eefab8307.png)

**Comment by MAKIO135** [comment]
this should considerably improve pen-up time 🤗

**Comment by nornagon** [comment]
Whoops! I'm a bit surprised this bug was there so long. Thanks for the fix!

**Comment by MAKIO135** [comment]
Thank you! 🙌
